import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Elevator } from '../components/elevator'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="bg-gray-300 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full">
        <Elevator />
      </main>

      <footer className="">
      </footer>
    </div>
  )
}

export default Home
